Post.create(title: 'My First Post', author: 'Justin Veirs', description: 'Holy Shit, more cowbell')
Post.create(title: 'My Second Post', author: 'Holy Shit', description: 'Holy Shit, more cowbell')
Post.create(title: 'My Third Post', author: 'Frizzle', description: 'Holy Shit, more cowbell')
Post.create(title: 'My Forth Post', author: 'Fry', description: 'Holy Shit, more cowbell')
Post.create(title: 'My Fifth Post', author: 'Justin Veirs', description: 'Holy Shit, more cowbell')
Post.create(title: 'My Sixth Post', author: 'Justin Veirs', description: 'Holy Shit, more cowbell')
